---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - operator.wnguddn777.com
  resources:
  - autodeploys
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - operator.wnguddn777.com
  resources:
  - autodeploys/finalizers
  verbs:
  - update
- apiGroups:
  - operator.wnguddn777.com
  resources:
  - autodeploys/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - policy.karmada.io
  resources:
  - propagationpolicies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
